### ISSUE TITLE
No documentation on using DNS with TLS

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb-python#223]
I started a new beta-3 instance and tried connecting to the DB from python. But I can't.

When I use the instance name it works fine
```python
conn = edgedb.connect('edgedb_quickstart')
```

But when I tried using the DSN address its not as simple
```python
conn = edgedb.connect('edgedb://edgedb:wL2JLb2G7By1KlbAd7uhZ49t@localhost:10701/edgedb')
```

> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)

**Comment by fantix** [comment]
I guess your scenario using DSN is to connect to an EdgeDB instance from a remote host? (Because I noticed you extracted the generated password from the credentials JSON file)

In order to connect to an EdgeDB instance created by the CLI tool on a remote host, you could now run `edgedb instance link` command to create a local link to the remote instance. When asked you can give the same name "`edgedb_quickstart`" to the local link so that your Python code `edgedb.connect('edgedb_quickstart')` would work on both hosts.

**Comment by Fogapod** [comment]
Hello, I've got the same issue. It happens both when using DNS or separate parameters like
```python
self.edb = edgedb.create_async_client(
    host=settings.EDGEDB_HOST,
    port=settings.EDGEDB_PORT,
    user=settings.EDGEDB_USER,
    password=settings.EDGEDB_PASSWORD,
    database=settings.EDGEDB_DATABASE,
)
```
Is creating instance link locally the only way to do this? I run my app inside docker container in a minimal alpine image, so I wouldn't want to have an extra dependency on edgedb cli if possible, especially since link creation only works interactively, would be a nightmare to run it from script. How does `link` work? Is there a way to do this without cli client?

> In order to connect to an EdgeDB instance created by the CLI tool on a remote host

Or maybe there is a way to configure my instance somehow?

**Comment by fantix** [comment]
> How does `link` work?

`link` retrieves the remote certificate and trusts it in future connections.

> Is there a way to do this without cli client?

You can use your own certificates for both the server and client, or tell the client to run in [insecure dev mode](https://www.edgedb.com/docs/reference/connection#granular-parameters).
